### PR TITLE
fix weird clampToPi function

### PR DESCRIPTION
**Pull request by dev10110**
Things weren't working well in my sims, so im pushing the  fix here.

### CODE REVIEW

**Comment by dev10110** [comment]
@hardikparwana can you confirm whether this is ok to merge?

**Comment by dev10110** [comment]
@chenrc98 can you verify this too?

**Review by hardikparwana — APPROVED** [review]
Sure, looks good and cleaner. Although, there's nothing weird about the current clamtoPi function lol. it's doing the exact same thing. It just assumes that the given angle is between -2pi and 2pi. The atan2 method will work though irrespective of the range of input yaw.

**Comment by chenrc98** [comment]
LGTM!

**Pull request merged**
